### ISSUE TITLE
XHR JSON RPC available via POST

### ISSUE THREAD

**Issue by hems** [ethereum/vapor#14]
I guess this happened cause i tried to open vapor without having AlethZero ( or other ethereum client ) running on my localhost ?

**Comment by kumavis** [comment]
vapor runs its own rpc -- you're hitting the rpc port instead of the web app port.
but as i mentioned in the other thread, this repo is deprecated and i need to add a notification.

**Comment by hems** [comment]
@kumavis ok cool. looking forward
