### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by hems** [ethereum/vapor#15]
after killing the process with CTRL+C when i try running it again i get the following error:

running master branch under Darwin
````
ethereum/vapor [ npm start                                                                                          master ] 11:30 pm

> vapor@0.0.0 start /Volumes/backpack/git/ethereum/vapor
> node rpc-server.js & gulp

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:742:11)
    at Server._listen2 (net.js:1148:14)
    at listen (net.js:1170:10)
    at Server.listen (net.js:1245:5)
    at Object.<anonymous> (/Volumes/backpack/git/ethereum/vapor/node_modules/node-ethereum/bin/dbServer:44:8)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)

/Volumes/backpack/git/ethereum/vapor/node_modules/node-webkit-builder/node_modules/archiver/node_modules/zip-stream/node_modules/lodash/index.js:664
  function runInContext(context) {
                       ^
illegal access
````

**Comment by kumavis** [comment]
Yeah this is node-ethereum. When it crashes or is forced closed it doesn't close one of its services, maybe the db-server
@wanderer this is why i suggested it to be a child_process so the lifecycle is connected

this repo is actually deprecated as we're currently rewriting the app in ember.
sorry that i have not marked it as such.

**Comment by hems** [comment]
@kumavis hey man, let's have a chat.

we have no reason to use ember or mercury, we can solve this more elegantly with smaller modules.

**Comment by kumavis** [comment]
absolutely -- just invited you to our Slack
If that doesn't work for you we can try something else

**Comment by hems** [comment]
@kumavis cheers!
